apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ibm-capstone-dealership
  name: ibm-capstone-dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ibm-capstone-dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: ibm-capstone-dealership
    spec:
      containers:
      - image: 0xaf2f6ad/ibm-capstone-dealership:latest
        imagePullPolicy: Always
        name: ibm-capstone-dealership
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always
  replicas: 1
